apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
  labels:
    app: apps
spec:
  selector:
    matchLabels:
      app: apps
  replicas: 1
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
        - name: apps
          image: eshan3312/vproapp:V1
          ports:
            - name: app-container
              containerPort: 8080
